# pre-commit-gate.ps1 — Quality gate before git commits
# Runs lint + tests before allowing commits.
# Generated by dev-workflow-builder (Enterprise tier).

$input_json = $input | ConvertFrom-Json
$command = $input_json.tool_input.command

# Only trigger on git commit commands
if ($command -notmatch '^\s*git\s+commit') {
    $result = @{
        hookSpecificOutput = @{
            hookEventName = "PreToolUse"
            permissionDecision = "allow"
        }
    }
    $result | ConvertTo-Json -Compress
    exit 0
}

# --- Quality Gate ---

$errors = @()
$warnings = @()

# 1) Lint check (HARD GATE — blocks commit)
$lintResult = & npm run lint 2>&1
if ($LASTEXITCODE -ne 0) {
    $errors += "LINT FAILED: Run 'npm run lint' to see details."
}

# 2) Tests (ADVISORY — warns but allows commit)
$testResult = & npm run test:run 2>&1
if ($LASTEXITCODE -ne 0) {
    $warnings += "TESTS WARNING: Run 'npm run test:run' to see details."
}

if ($errors.Count -gt 0) {
    $reason = "CODE QUALITY GATE BLOCKED COMMIT:`n" + ($errors -join "`n") + "`nFix these issues before committing."
    $result = @{
        hookSpecificOutput = @{
            hookEventName = "PreToolUse"
            permissionDecision = "deny"
            permissionDecisionReason = $reason
        }
    }
    $result | ConvertTo-Json -Compress
    exit 0
}

if ($warnings.Count -gt 0) {
    $reason = "CODE QUALITY WARNINGS (commit allowed):`n" + ($warnings -join "`n")
    $result = @{
        hookSpecificOutput = @{
            hookEventName = "PreToolUse"
            permissionDecision = "allow"
            permissionDecisionReason = $reason
        }
    }
    $result | ConvertTo-Json -Compress
    exit 0
}

# All checks passed
$result = @{
    hookSpecificOutput = @{
        hookEventName = "PreToolUse"
        permissionDecision = "allow"
    }
}
$result | ConvertTo-Json -Compress
exit 0
