/**
 * Draft Export (FF-054)
 *
 * Export draft results as CSV or generate a shareable summary.
 */

import type { DraftPick } from '@/lib/draft/state'
import type { DraftReview } from '@/lib/draft/review'

/**
 * Generate CSV string from draft picks
 */
export function picksToCSV(
  picks: DraftPick[],
  format: 'auction' | 'snake',
): string {
  const headers = format === 'auction'
    ? ['Pick #', 'Manager', 'Player', 'Position', 'Price']
    : ['Pick #', 'Manager', 'Player', 'Position', 'Round']

  const rows = picks.map(p => {
    const base = [
      String(p.pick_number),
      p.manager,
      p.player_name,
      p.position || '',
    ]
    if (format === 'auction') {
      base.push(p.price != null ? String(p.price) : '')
    } else {
      base.push(p.round != null ? String(p.round) : '')
    }
    return base
  })

  const escape = (s: string) => {
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`
    }
    return s
  }

  return [
    headers.map(escape).join(','),
    ...rows.map(r => r.map(escape).join(',')),
  ].join('\n')
}

/**
 * Generate a plain-text shareable summary of the draft
 */
export function reviewToShareText(
  review: DraftReview,
  managerName: string,
  format: 'auction' | 'snake',
  strategyName?: string,
): string {
  const lines: string[] = []

  lines.push(`DRAFT REVIEW — ${managerName}`)
  lines.push(`Grade: ${review.overallGrade} (${review.overallScore}/100)`)
  lines.push(review.summary)
  lines.push('')

  if (strategyName) {
    lines.push(`Strategy: ${strategyName}`)
    lines.push('')
  }

  if (review.strengths.length > 0) {
    lines.push('STRENGTHS:')
    for (const s of review.strengths) lines.push(`  + ${s}`)
    lines.push('')
  }

  if (review.weaknesses.length > 0) {
    lines.push('AREAS TO IMPROVE:')
    for (const w of review.weaknesses) lines.push(`  - ${w}`)
    lines.push('')
  }

  lines.push('POSITION GRADES:')
  for (const pg of review.positionGrades) {
    const playerList = pg.picks.map(p => {
      const cost = p.price != null ? ` ($${p.price})` : p.round != null ? ` (Rd ${p.round})` : ''
      return `${p.name}${cost}`
    }).join(', ')
    lines.push(`  ${pg.position}: ${pg.grade} — ${playerList}`)
  }
  lines.push('')

  if (review.targetResults.length > 0) {
    lines.push('STRATEGY TARGETS:')
    for (const tr of review.targetResults) {
      const icon = tr.status === 'hit' ? 'HIT' : tr.status === 'missed' ? 'MISS' : tr.status === 'avoided_success' ? 'AVOIDED' : 'DRAFTED'
      lines.push(`  [${icon}] ${tr.playerName} — ${tr.detail}`)
    }
    lines.push('')
  }

  if (review.budgetAnalysis) {
    lines.push(`BUDGET: $${review.budgetAnalysis.totalSpent}/$${review.budgetAnalysis.totalBudget} spent (avg $${review.budgetAnalysis.avgPrice}/pick)`)
  }

  lines.push('')
  lines.push('Generated by Fantasy Draft Advisor')

  return lines.join('\n')
}

/**
 * Trigger a CSV file download in the browser
 */
export function downloadCSV(csv: string, filename: string) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}
